### ISSUE TITLE
Native promise logs error when using Jasmine and rejecting a promise

### ISSUE THREAD

**Issue by Almenit** [charleshansen/mock-promises#26] opened 2016-11-14 16:33 UTC
In Chrome I get:
Uncaught (in promise) Error: failing action
    at Object.<anonymous> (all.js:59874)
    at attemptAsync (jasmine.js:1790)
    at QueueRunner.run (jasmine.js:1746)

And chutzpah logs Error: Unhandled promise rejection Error: failing action 

The issue is not that the test fails but that when runing it it logs errors and that casues our build server to issue warnings.

The reject is not unhandled, that is what I am testing making sure it is handled in the right way.
We have updated our jasmine and mock-promises packages and now we have this issue.
If I don't use mock-promises (using only native promises) )I don't get the error.

**Comment by Almenit** [comment] 2016-11-15 14:22
I'm not sure how to do this. I added an handler for onunhandledrejection. It is my mocked rejected promise that is unhandled.

```javascript
//Test
savePromise = mockPromises.getMockPromise(Promise).reject(new Error("Report this"));
saveStub = sinon.stub().returns(savePromise);
proxy.SessionProxy.save = saveStub;
...
mockPromises.executeForPromise(savePromise);
mockPromises.executeForResolvedPromises();

//Executing code
proxy.SessionProxy.delete({ id: id })
        .then(() => {
            appDispatcher.handleViewAction({
                type: Constants.ModalDialog.Actions.HIDE_MODAL_DIALOG,
                payload: {}
            });

            appDispatcher.handleViewAction({
                type: Constants.Session.Actions.DELETED_SESSION,
                payload: { id: id }
            });
        })
        .catch((err) => {
            appDispatcher.handleViewAction({
                type: Constants.ModalDialog.Actions.HIDE_MODAL_DIALOG,
                payload: {}
            });
        });

**Comment by charleshansen** [comment] 2016-11-18 16:07
Trying to reproduce this now, was this only a problem after you upgrade mock-promises? What version were you using where it worked?

**Comment by charleshansen** [comment] 2016-11-18 16:21
It also looks like you are mocking the promise from `proxy.SessionProxy.save` but not `proxy.SessionProxy.delete`, you should really mock all promises at the same time, I'm not sure what happens if one promise is mocked but another one isn't. 

You should mock all promises by replacing `window.Promise = mockPromises.getMockPromise(Promise)` or possibly `global.Promise = ....` if you are in node

**Comment by charleshansen** [comment] 2016-11-18 16:36
Hopefully fixed in 0.8.1, give it a shot.

This was a real issue that has been around for a while. I just never failed a build from errors in Chrome and it doesn't happen in Phantom because there aren't native promises there.

**Comment by charleshansen** [comment] 2017-02-06 16:21
fixed

**Closed by charleshansen** 2017-02-06 16:21 UTC

**Comment by sebastianrothbucher** [comment] 2017-05-12 15:50
Just 2 be aware: for mocking native promises ``` Promise=mockPromises.getMockPromise(Promise)``` and preparing rejected promises as return values, there's a difference between
```
Promise.reject("someerr");
```
and
```
Promise.resolve().then(() => {throw "someerr";});
mockPromises.tick();
```
as the lower solution avoids misleading / incorrect "UnhandledPromiseRejectionWarning: Unhandled promise rejection" warnings (maybe errors in newer versions) in nodeJS (running Jest in my case)

**Comment by sebastianrothbucher** [comment] 2017-05-12 18:01
additionally (& assuming one doesn't want the rejection warning), could we not go w/out native promises in the first place? Like e.g. this: https://github.com/charleshansen/mock-promises/compare/master...sebastianrothbucher:mockonly?expand=1 ?
Maybe one could even do a flag turning delegation on and off
